In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df = pd.read_csv("../Data/AQI and Lat Long of Countries.csv")
df

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category,lat,lng
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate,44.7444,44.2031
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good,-5.2900,-44.4900
2,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good,-11.2958,-41.9869
3,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate,37.1667,15.1833
4,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good,53.0167,20.8833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16690,United States of America,Highland Springs,54,Moderate,1,Good,34,Good,5,Good,54,Moderate,37.5516,-77.3285
16691,Slovakia,Martin,71,Moderate,1,Good,39,Good,1,Good,71,Moderate,49.0650,18.9219
16692,Slovakia,Martin,71,Moderate,1,Good,39,Good,1,Good,71,Moderate,36.3385,-88.8513
16693,France,Sceaux,50,Good,1,Good,20,Good,5,Good,50,Good,48.7786,2.2906
16694,United States of America,Westerville,71,Moderate,1,Good,44,Good,2,Good,71,Moderate,40.1241,-82.9210

In [21]:
df.isnull().sum()

Country               302
City                    0
AQI Value               0
AQI Category            0
CO AQI Value            0
CO AQI Category         0
Ozone AQI Value         0
Ozone AQI Category      0
NO2 AQI Value           0
NO2 AQI Category        0
PM2.5 AQI Value         0
PM2.5 AQI Category      0
lat                     0
lng                     0
dtype: int64

In [22]:
df['Country'] = df['Country'].fillna('Unknown')

In [23]:
df = df.drop_duplicates()
df

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category,lat,lng
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate,44.7444,44.2031
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good,-5.2900,-44.4900
2,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good,-11.2958,-41.9869
3,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate,37.1667,15.1833
4,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good,53.0167,20.8833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16690,United States of America,Highland Springs,54,Moderate,1,Good,34,Good,5,Good,54,Moderate,37.5516,-77.3285
16691,Slovakia,Martin,71,Moderate,1,Good,39,Good,1,Good,71,Moderate,49.0650,18.9219
16692,Slovakia,Martin,71,Moderate,1,Good,39,Good,1,Good,71,Moderate,36.3385,-88.8513
16693,France,Sceaux,50,Good,1,Good,20,Good,5,Good,50,Good,48.7786,2.2906
16694,United States of America,Westerville,71,Moderate,1,Good,44,Good,2,Good,71,Moderate,40.1241,-82.9210

In [24]:
df.isnull().sum()

Country               0
City                  0
AQI Value             0
AQI Category          0
CO AQI Value          0
CO AQI Category       0
Ozone AQI Value       0
Ozone AQI Category    0
NO2 AQI Value         0
NO2 AQI Category      0
PM2.5 AQI Value       0
PM2.5 AQI Category    0
lat                   0
lng                   0
dtype: int64

In [25]:
df.nunique()

Country                 175
City                  14229
AQI Value               282
AQI Category              6
CO AQI Value             31
CO AQI Category           3
Ozone AQI Value         203
Ozone AQI Category        5
NO2 AQI Value            56
NO2 AQI Category          2
PM2.5 AQI Value         298
PM2.5 AQI Category        6
lat                   14135
lng                   14896
dtype: int64

In [26]:
df['AQI Category'].unique()

array(['Moderate', 'Good', 'Unhealthy', 'Very Unhealthy',
       'Unhealthy for Sensitive Groups', 'Hazardous'], dtype=object)

In [27]:
df = df.replace('Good',1)
df = df.replace('Moderate',2)
df = df.replace('Unhealthy',3)
df = df.replace('Very Unhealthy',4)
df = df.replace('Unhealthy for Sensitive Groups',5)
df = df.replace('Hazardous',6)

C:\Users\NAYAN ADHIKARI\AppData\Local\Temp\ipykernel_6508\3194555296.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('Moderate',2)
C:\Users\NAYAN ADHIKARI\AppData\Local\Temp\ipykernel_6508\3194555296.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('Unhealthy for Sensitive Groups',5)
C:\Users\NAYAN ADHIKARI\AppData\Local\Temp\ipykernel_6508\3194555296.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('Hazardous',6)

In [28]:
df.nunique()

Country                 175
City                  14229
AQI Value               282
AQI Category              6
CO AQI Value             31
CO AQI Category           3
Ozone AQI Value         203
Ozone AQI Category        5
NO2 AQI Value            56
NO2 AQI Category          2
PM2.5 AQI Value         298
PM2.5 AQI Category        6
lat                   14135
lng                   14896
dtype: int64

In [29]:
df

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category,lat,lng
0,Russian Federation,Praskoveya,51,2,1,1,36,1,0,1,51,2,44.7444,44.2031
1,Brazil,Presidente Dutra,41,1,1,1,5,1,1,1,41,1,-5.2900,-44.4900
2,Brazil,Presidente Dutra,41,1,1,1,5,1,1,1,41,1,-11.2958,-41.9869
3,Italy,Priolo Gargallo,66,2,1,1,39,1,2,1,66,2,37.1667,15.1833
4,Poland,Przasnysz,34,1,1,1,34,1,0,1,20,1,53.0167,20.8833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16690,United States of America,Highland Springs,54,2,1,1,34,1,5,1,54,2,37.5516,-77.3285
16691,Slovakia,Martin,71,2,1,1,39,1,1,1,71,2,49.0650,18.9219
16692,Slovakia,Martin,71,2,1,1,39,1,1,1,71,2,36.3385,-88.8513
16693,France,Sceaux,50,1,1,1,20,1,5,1,50,1,48.7786,2.2906
16694,United States of America,Westerville,71,2,1,1,44,1,2,1,71,2,40.1241,-82.9210

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16695 entries, 0 to 16694
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country             16695 non-null  object
 1   City                16695 non-null  object
 2   AQI Value           16695 non-null  int64
 3   AQI Category        16695 non-null  int64
 4   CO AQI Value        16695 non-null  int64
 5   CO AQI Category     16695 non-null  int64
 6   Ozone AQI Value     16695 non-null  int64
 7   Ozone AQI Category  16695 non-null  int64
 8   NO2 AQI Value       16695 non-null  int64
 9   NO2 AQI Category    16695 non-null  int64
 10  PM2.5 AQI Value     16695 non-null  int64
 11  PM2.5 AQI Category  16695 non-null  int64
 12  lat                 16695 non-null  float64
 13  lng                 16695 non-null  float64
dtypes: float64(2), int64(10), object(2)
memory usage: 1.8+ MB

In [34]:
df.to_csv("../Data/AQI and Lat Long of Countries_cleaned.csv",index= False)